name: NestBook CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Update dependencies automatically
        run: |
          npm install -g npm-check-updates
          ncu -u  # Automatically updates the package.json with latest versions
          npm install  # Reinstall the updated dependencies

      - name: Build the project
        run: npm run build
